name: CI Pipeline - Flask Docker Helm

on:
  push:
    branches: [ main ]

    paths-ignore:
        - README.md

jobs:
  trivy-fs-scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Trivy File System Scan
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: 'fs'
          scan-ref: '.'
          trivy-config: trivy.yaml

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
  
  sast:
    needs: trivy-fs-scan
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Install nodejsscan
        run: pip install nodejsscan

      - name: Run SAST Scan
        run: |
          nodejsscan -d . -o sast-report.json
          cat sast-report.json

      - name: Upload SAST Report
        uses: actions/upload-artifact@v4
        with:
          name: sast-report
          path: sast-report.json
        
  docker-build-push:
    name: Build & Push Docker Image
    runs-on: ubuntu-latest
    needs: sast
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/internship:${{ github.run_id }}
      
      - name: Trivy Image Scan
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: ${{ secrets.DOCKERHUB_USERNAME }}/internship:${{ github.run_id }}
          format: 'table'
          exit-code: '0'
          ignore-unfixed: true
  
  update-newtag-in-helm-chart:
    runs-on: ubuntu-latest

    needs: docker-build-push

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.TOKEN }}

    - name: Update tag in Helm chart
      run: |
        sed -i 's/tag: .*/tag: "${{github.run_id}}"/' helm/hlem_charts/values.yaml

    - name: Commit and push changes
      run: |
        git config --global user.email "bhandariayush960@gmail.com"
        git config --global user.name "Ayushgittt"
        git add helm/hlem_charts/values.yaml
        git commit -m "Update tag in Helm chart"
        git push        